# scripts to run before build
before_build:
  - echo Running cmake...
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target INSTALL
  - cd ..

after_build:
  - 7z a micmac_win.zip bin\ binaire-aux\ include\XML_MicMac\ include\XML_MicMac\
  
artifacts:
  path: micmac_win.zip
  name: micmac_win
