# scripts to run before build
before_build:
  - echo Running cmake...
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target INSTALL

after_build:
  - 7z a micmac_win.zip *
  
artifacts:
  path: build\micmac_win.zip
  name: micmac_win
